### PR TITLE
[CAZSM-242] Security patching (puma, nokogiri, browserslist)

### PR DESCRIPTION
**Pull request by leusoijames**
## Checklist:

- [ ] It contains only changes required by issue (does not contain other PR)
- [ ] Includes a link to an issue (if apply)
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by leusoijames** [comment]
@likeuwill Hi Sergii, please could I get some of your input on this. It seems like a change to rubocop: https://github.com/rubocop/rubocop-rails/blob/master/config/default.yml#L264, has caused the build to fail with a 'Do not read from ENV directly post initialization' during the static code tests. This happens whenever an ENV.fetch() occurs.

I've tried changing rubocop to a version that matches Payments UI however, that causes the build to fail during the build phase. Do you have any advice on what to do in this situation? Fully revert rubocop to its initial values?

**Comment by likeuwill** [comment]
Hi, @leusoijames. If it's ok for you i added `.iyarc` file to ignore one yarn warning which we cant fix, also fixed rubocop warning and updated libs. Now CI will pass.

**Review by likeuwill — APPROVED** [review]

**Comment by leusoijames** [comment]
Hi, @likeuwill, thanks for taking a look. I have a quick question, as this will need to be done on all the UI layers. Did you just bump these and ran a bundle update: 
@rails/webpacker": "^5.4.0", 
 "govuk-frontend": "^3.12.0",   
 "improved-yarn-audit": "^2.3.3

As for the rubocop issue, we will just be ignoring that on all UI layers?

**Comment by likeuwill** [comment]
> Hi, @likeuwill, thanks for taking a look. I have a quick question, as this will need to be done on all the UI layers. Did you just bump these and ran a bundle update: 
> @rails/webpacker": "^5.4.0", 
>  "govuk-frontend": "^3.12.0",   
>  "improved-yarn-audit": "^2.3.3
> 
> As for the rubocop issue, we will just be ignoring that on all UI layers? 
> 
> 
> 

Yes, just bump versions('bundle update' and 'ncu -u' and then 'yarn install' and 'yarn upgrade'). Also check '.iyarc' file, atm we should have only one I'd in exclude list.

**Pull request merged**
